- name: git checkout code latest
  git:
    repo: 'https://github.com/piyapanhub/workshop-v1.git'
    dest: /tmp/workshop-dev1
    version: master

- name: Build docker images
  command: docker build -f /tmp/workshop-dev1/Dockerfile -t piyapanker/workshop1:"{{ tagnumber }}" /tmp/workshop-dev1

- name: Docker tag images
  command: docker tag piyapanker/workshop1:"{{ tagnumber }}" piyapanker/workshop1:latest

- name: Docker push
  command: docker push piyapanker/workshop1:latest 
